### PR TITLE
sample sets page: remove sample sets

### PR DESCRIPTION
**Pull request by hannamlmv**
Add a functionality to remove sample sets previously added by the user (i.e. not predefined sample sets)

### CODE REVIEW

**Comment by hannamlmv** [comment]
I am attempting to add a way to remove the added sample sets (not the predefined ones). The layout of the menu has been changed successfully (see image below) however the remove function is not fully functional. You can only remove the most recently added sample. If you try to remove previous samples it only works once you have first removed all later samples. 

Skärmavbild 2024-11-29 kl  12 54 29

I think this bug is related to the fact that the "drop" function of the DataFrame is set to inplace=True, as we want to original data to be updated, we don't want a copy of it. This seems to cause some issues with the updating of the tabulator, however the DataFrame itself is updated (which can be seen if you print it). I can't figure out how to solve this bug right now, so I'm leaving it here as draft code.

**Comment by tforest** [comment]
Maybe another approach would be to toggle a "enabled"/"disabled" status for each sample set, as it might be a little dangerous to be able to remove a sample set from the original dataset by a simple click without being able to restore it. Also, I would suggest to add a checkbox in the table itself to toggle each sample set, instead of putting this option in the sidebar. ;)

**Comment by hannamlmv** [comment]
we wont focus on fixing this, so closing it

**Comment by hannamlmv** [comment]
> Maybe another approach would be to toggle a "enabled"/"disabled" status for each sample set, as it might be a little dangerous to be able to remove a sample set from the original dataset by a simple click without being able to restore it. I say this keeping the idea that the modifications will be saved and would be restored after closing the browser, in the long term. Also, I would suggest to add a checkbox in the table itself to toggle each sample set, instead of putting this option in the sidebar. ;)

In the implementation in this PR, it was never possible to remove the original sample sets, only the ones added by the user. The toggle (enable/disable) functionality is already available on the individuals page, which is one reason why we chose to close this issue.

**Comment by tforest** [comment]
> > Maybe another approach would be to toggle a "enabled"/"disabled" status for each sample set, as it might be a little dangerous to be able to remove a sample set from the original dataset by a simple click without being able to restore it. I say this keeping the idea that the modifications will be saved and would be restored after closing the browser, in the long term. Also, I would suggest to add a checkbox in the table itself to toggle each sample set, instead of putting this option in the sidebar. ;)
> 
> In the implementation in this PR, it was never possible to remove the original sample sets, only the ones added by the user. The toggle (enable/disable) functionality is already available on the individuals page, which is one reason why we chose to close this issue.

Sounds good to me!

**Pull request closed without merging**
